<a href="https://colab.research.google.com/github/Lihua-Xiao/LX/blob/master/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Scalar or 0D Tensor

In [ ]:
x = np.array(1)
print(x)
print(x.ndim)

1
0


Vectors or 1D Tensor

In [ ]:
x = np.array([1,2,3,4,5])
print(x)
print(x.ndim)

[1 2 3 4 5]
1


Matrices or 2D Tensors


In [ ]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x)
print(x.ndim)
print(x.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)


3D Tensors

In [ ]:
x = np.array([ [[1,2,3,4,5],[6,7,8,9,10]],
              [[11,12,13,14,15],[16,17,18,19,20]] 
            ])
print(x)
print(x.ndim)
print(x.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
3
(2, 2, 5)
